const configs={siliconflow:{chat:'https://api.siliconflow.cn/v1/chat/completions',asr:'https://api.siliconflow.cn/v1/audio/transcriptions',chatModel:'Qwen/Qwen3.5-4B',asrModel:'FunAudioLLM/SenseVoiceSmall'}};
chrome.runtime.onInstalled.addListener(() => chrome.sidePanel.setPanelBehavior({openPanelOnActionClick: true}));
chrome.action.onClicked.addListener(tab => { if (tab.id) chrome.sidePanel.open({tabId: tab.id}).catch(() => {}); });
async function getConfig(){const s=await chrome.storage.sync.get(['provider','apiKey','model']);const provider=s.provider||'siliconflow';return {...configs[provider],provider,apiKey:s.apiKey||'',chatModel:s.model||configs[provider].chatModel};}
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{
  if(message.type==='FETCH_SUBTITLE'){const url=message.url.startsWith('//')?'https:'+message.url:message.url;fetch(url).then(r=>r.json()).then(d=>sendResponse({ok:true,text:(d.body||d.data?.body||[]).map(x=>{const sec=Number(x.from??x.start??x.start_time);const stamp=Number.isFinite(sec)?`[${String(Math.floor(sec/60)).padStart(2,'0')}:${String(Math.floor(sec%60)).padStart(2,'0')}] `:'';return stamp+(x.content||x.text||'');}).join(' ')})).catch(e=>sendResponse({ok:false,error:String(e)}));return true;}
  if(message.type==='SUMMARIZE_VIDEO'){(async()=>{try{const c=await getConfig();if(!c.apiKey)throw Error('请先在设置中填写 API Key');const title=String(message.title||'B站视频').slice(0,500),content=String(message.content||'').slice(0,50000);const r=await fetch(c.chat,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${c.apiKey}`},body:JSON.stringify({model:c.chatModel,temperature:.3,max_tokens:1200,messages:[{role:'system',content:'你是可靠、简洁的中文视频总结助手。'},{role:'user',content:`请总结下面的中文视频内容。严格输出：一句话总结、关键要点。只有原文中出现 [分钟:秒] 时间标记时，才在对应要点前保留该时间标记；如果原文没有时间标记，就完全不要提及时间戳。不要输出适合谁看、行动建议或其他栏目。只根据提供的内容，不要编造。\n\n视频标题：${title}\n视频内容：\n${content}`}]})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||`请求失败（${r.status}）`);sendResponse({ok:true,summary:d.choices?.[0]?.message?.content||''});}catch(e){sendResponse({ok:false,error:String(e)});}})();return true;}
  if(message.type==='TRANSCRIBE_AUDIO'){(async()=>{try{const c=await getConfig();if(!c.apiKey)throw Error('请先在设置中填写 API Key');if(!c.asr)throw Error('当前服务商不支持语音识别，请改用 OpenAI 或 SiliconFlow');const bytes=Uint8Array.from(atob(message.audio),x=>x.charCodeAt(0));const form=new FormData();form.append('file',new Blob([bytes],{type:message.mimeType||'audio/webm'}),'bilibili-audio.webm');form.append('model',c.asrModel);form.append('response_format','verbose_json');const r=await fetch(c.asr,{method:'POST',headers:{'Authorization':`Bearer ${c.apiKey}`},body:form});const d=await r.json();if(!r.ok)throw Error(d.error?.message||`语音识别失败（${r.status}）`);sendResponse({ok:true,text:d.text||'',segments:d.segments||[]});}catch(e){sendResponse({ok:false,error:String(e)});}})();return true;}
  if(message.type==='DOWNLOAD_AUDIO'){(async()=>{try{const r=await fetch(message.url);if(!r.ok)throw Error(`音频下载失败（${r.status}）`);const b=new Uint8Array(await r.arrayBuffer());let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));sendResponse({ok:true,audio:btoa(s),mimeType:'audio/mp4'});}catch(e){sendResponse({ok:false,error:String(e)});}})();return true;}
  if(message.type==='FOLLOWUP'){(async()=>{try{const c=await getConfig();if(!c.apiKey)throw Error('请先在设置中填写 API Key');const prompt=`视频标题：${message.title||''}\n视频总结：${message.summary||''}\n原始文本：${String(message.content||'').slice(0,40000)}\n\n用户问题：${message.question}`;const r=await fetch(c.chat,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${c.apiKey}`},body:JSON.stringify({model:c.chatModel,temperature:.3,max_tokens:900,messages:[{role:'system',content:'你是视频问答助手，只根据视频内容回答问题；信息不足时明确说明。'},{role:'user',content:prompt}]})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||`请求失败（${r.status}）`);sendResponse({ok:true,answer:d.choices?.[0]?.message?.content||''});}catch(e){sendResponse({ok:false,error:String(e)});}})();return true;}
});
