const $=s=>document.querySelector(s);let info=null,transcript='',summary='';let lang=localStorage.getItem('vs-lang')||'zh';
const i18n={zh:{title:'视频总结',subtitle:'视频、网课和讲座都可以总结',settings:'设置',reading:'正在读取当前页面…',summarize:'生成总结',summaryTab:'总结',textTab:'原始文本',chatTab:'继续追问',questionPlaceholder:'针对这个视频继续提问',send:'发送',noVideo:'当前页面没有可识别的视频',loading:'正在整理视频内容…',done:'总结完成',noText:'没有获取到可用文本',failed:'处理失败：'},en:{title:'Video Summary',subtitle:'Summarize videos, courses, and lectures',settings:'Settings',reading:'Reading the current page…',summarize:'Generate summary',summaryTab:'Summary',textTab:'Source text',chatTab:'Follow-up',questionPlaceholder:'Ask a follow-up question about this video',send:'Send',noVideo:'No recognizable video on this page',loading:'Processing video content…',done:'Summary complete',noText:'No usable text was found',failed:'Failed: '}};
function t(k){return i18n[lang][k]||k}function renderLang(){document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder));$('#langToggle').textContent=lang==='zh'?'EN':'中';document.documentElement.lang=lang==='zh'?'zh-CN':'en';}
$('#langToggle').onclick=()=>{lang=lang==='zh'?'en':'zh';localStorage.setItem('vs-lang',lang);renderLang();};renderLang();
async function getTab(){return (await chrome.tabs.query({active:true,currentWindow:true}))[0];}
async function load(){const tab=await getTab();if(!tab){$('#video').textContent=t('noVideo');return;}chrome.tabs.sendMessage(tab.id,{type:'GET_VIDEO_INFO'},response=>{if(chrome.runtime.lastError||!response?.ok){$('#video').textContent=t('noVideo');return;}info=response.payload;$('#video').innerHTML=`<strong>${info.title||'Video'}</strong><br><span>${info.site||''}</span>`;$('#summarize').disabled=false;});}
load();
$('#summarize').onclick=async()=>{try{$('#summarize').disabled=true;$('#status').textContent=t('loading');if(info.subtitles?.[0]?.url){const r=await chrome.runtime.sendMessage({type:'FETCH_SUBTITLE',url:info.subtitles[0].url});transcript=r.text||'';}if(!transcript.trim()&&info.audioUrl){const r=await chrome.runtime.sendMessage({type:'DOWNLOAD_AUDIO',url:info.audioUrl});if(r?.ok){const x=await chrome.runtime.sendMessage({type:'TRANSCRIBE_AUDIO',audio:r.audio,mimeType:r.mimeType});transcript=x.text||'';}}if(!transcript.trim()){const tab=await getTab();const r=await chrome.tabs.sendMessage(tab.id,{type:'CAPTURE_AUDIO'});if(r?.ok){const x=await chrome.runtime.sendMessage({type:'TRANSCRIBE_AUDIO',audio:r.audio,mimeType:r.mimeType});transcript=x.text||'';}}if(!transcript.trim()){summary=t('noText');}else{const r=await chrome.runtime.sendMessage({type:'SUMMARIZE_VIDEO',title:info.title,content:transcript});if(!r?.ok)throw Error(r?.error||'API error');summary=r.summary||t('noText');}$('#summary').textContent=summary;$('#transcript').textContent=transcript||t('noText');$('#status').textContent=t('done');}catch(e){$('#status').textContent=t('failed')+e.message;}finally{$('#summarize').disabled=false;}};
document.querySelectorAll('nav [data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav [data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==b.dataset.view);});
$('#chatForm').onsubmit=async e=>{e.preventDefault();const q=$('#question').value.trim();if(!q||!transcript)return;$('#question').value='';const add=(role,text)=>{const div=document.createElement('div');div.className='message '+role;div.textContent=text;$('#messages').appendChild(div);};add('user',q);try{const r=await chrome.runtime.sendMessage({type:'FOLLOWUP',title:info?.title,content:transcript,summary,question:q});if(!r?.ok)throw Error(r?.error||'API error');add('assistant',r.answer);}catch(e){add('assistant',t('failed')+e.message);}};
$('#settings').onclick=()=>chrome.runtime.openOptionsPage();
